name: Question (English)
description: Ask a question about the project.
# title: "[Bug]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting Issue, please star the repo to help more people discover this project.

  - type: textarea
    attributes:
      label: Question
      description: What is your question?
      placeholder: |
        Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?
